<a href="https://colab.research.google.com/github/Nikhil29/ProductRecommendation/blob/master/userInterestFind.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#import initial libraries

import numpy as np
import pandas as pd
import datetime

import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display # Allows the use of display() for displaying DataFrames

In [96]:
# Read the data

data = pd.read_csv('https://query.data.world/s/nf4coj2x5ecz5hqr3kmf5e2hf2fzhk')
data.drop(columns=['dateUpdated', 'ean', 'imageURLs', 'sourceURLs', 'upc', 'keys', 'name', 'reviews.date', 'reviews.dateSeen', 'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs', 'reviews.text', 'reviews.title', 'reviews.username'], inplace=True)
data.drop_duplicates(inplace=True)
data.dropna(inplace=True)
data['categories'] = data['categories'].str.split(',')
data['categories'] = data['categories'].apply(tuple)
data['colors'] = data['colors'].str.split(',')
data['colors'] = data['colors'].apply(tuple)
display(data.head())

                        id  ...                                             weight
0     AVpf3txeLJeJML43FN82  ...                                         1.1 pounds
507   AVpgMuGwLJeJML43KY_c  ...                                       14.55 pounds
1109  AVpgF1BOilAPnD_xnTsK  ...                                        12.5 ounces
1689  AVzNjwZZ-jtxr-f3yc_y  ...                                        1.25 pounds
1970  AVpg8i6NilAPnD_xzQdN  ...  1.8 lbs                                       ...

[5 rows x 11 columns]

In [97]:
# Find the frequecy of every combinations

# already computed column cominations
compColComb = []

# final freq data frame
finalFreqData = pd.DataFrame(columns=np.append(data.columns.values, "Freq"))

def findFreq(combData):
  global compColComb;
  global finalFreqData;

  # check if the size of the columns is 0
  if combData.columns.size == 0:
    return

  # check if this set of columns the freq has already been computed
  if tuple(combData.columns.values) in compColComb:
    return

  # the freq is computed
  compColComb.append(tuple(combData.columns.values))

  # compute freq
  freqData = combData.groupby(list(combData.columns)).size().reset_index(name="Freq")
  freqData = freqData[(freqData['Freq'] >= 0.3 * combData.shape[0])]
  finalFreqData = finalFreqData.append(freqData, sort=True)
  for col in combData.columns:
    findFreq(combData.drop(columns=[col]))

# finally find the freq for the dataset
findFreq(data)
display(finalFreqData)

  Freq asins brand  ... manufacturerNumber primaryCategories weight
0   16   NaN   NaN  ...                NaN       Electronics    NaN
0    5   NaN   NaN  ...                NaN               NaN    NaN
0    5   NaN   NaN  ...                NaN       Electronics    NaN

[3 rows x 12 columns]